site_name: ArgMax
theme:
  name: material
  features:
    - navigation.tabs # Optional: Moves top-level sections into a horizontal top bar


repo_url: https://github.com/ontoligent/argmax
edit_uri: edit/main/docs/

# Custom Navigation Map
nav:
  - Home: index.md
  - Seminars:
    - Foundations of Data Science: seminars/fds/index.md

markdown_extensions:
  - admonition
  - pymdownx.details # Required ONLY if you want collapsible (foldable) blocks
  - pymdownx.superfences # Highly recommended to prevent parsing conflicts


plugins:
  - search
  - mermaid2